version: '2'

services:
    app:
        networks:
            - default
        build:

#        https://github.com/nodejs/docker-node/issues/78
#        The :onbuild image variant requires a package.json to be in the same directory as your Dockerfile.
#        (-_-')
#            context: .
#            dockerfile: ./docker/app/Dockerfile
            context: ./app
            dockerfile: Dockerfile
        container_name: app

    web:
        networks:
            - default
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: nginx
        ports:
            - 0.0.0.0:80:80
        depends_on:
            - app

